In [1]:
import pandas as pd
from googletrans import Translator

In [2]:
#importando os datasets
jogos = pd.read_csv(r'C:\Users\mathe\OneDrive\Área de Trabalho\Matheus\WorldCup\WorldCupMatches.csv', encoding='ISO-8859-1')
campeoes = pd.read_csv(r'C:\Users\mathe\OneDrive\Área de Trabalho\Matheus\WorldCup\WorldCups.csv', encoding='ISO-8859-1')

# Tratando a tabela jogos

In [3]:
jogos
#Identificado  valores NaN no fim da tabela

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#verifica quantos valores é null na tabela
jogos.isnull().sum()
#Coluna 'attendance' possui 2 valores nulos a mais

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [5]:
#Limpando dados NaN da tabela jogos, onde a coluna 'Year" é NaN, e ignorando os 2 valores NaN na coluna 'Attendence'
jogos.dropna(subset=['Year'],inplace=True)
jogos

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0.0,0.0,Costa Rica,Netherlands win on penalties (4 - 3),51179.0,0.0,0.0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953.0,300186488.0,NED,CRC
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,58141.0,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0.0,0.0,Argentina,Argentina win on penalties (2 - 4),63267.0,0.0,0.0,Cï¿½neyt ï¿½AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955.0,300186490.0,NED,ARG
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,,68034.0,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957.0,300186502.0,BRA,NED
851,2014.0,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time,74738.0,0.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959.0,300186501.0,GER,ARG

In [6]:
#Procura valores diferentes e unicos em cada coluna(outliers)
for coluna in jogos:
    count_jogos = jogos[coluna].value_counts()
    print(count_jogos)
 
# Encontrado nomes errados na coluna Home Team Name
# Encontrado nomes errados na coluna Stadium

2014.0    80
2010.0    64
2006.0    64
2002.0    64
1998.0    64
1982.0    52
1994.0    52
1990.0    52
1986.0    52
1978.0    38
1974.0    38
1958.0    35
1970.0    32
1966.0    32
1962.0    32
1954.0    26
1950.0    22
1938.0    18
1930.0    18
1934.0    17
Name: Year, dtype: int64
27 May 1934 - 16:30     8
11 Jun 1958 - 19:00     7
08 Jun 1958 - 19:00     7
15 Jun 1958 - 19:00     7
06 Jun 1970 - 16:00     4
                       ..
24 Jun 1994 - 19:30     1
24 Jun 1994 - 12:30     1
23 Jun 1994 - 19:30     1
23 Jun 1994 - 16:00     1
04 Jul 1998 - 21:00     1
Name: Datetime, Length: 602, dtype: int64
Round of 16                 72
Quarter-finals              66
Group 1                     62
Group A                     60
Group B                     60
Group 2                     59
Group 3                     56
Group 4                     55
Group C                     48
Group D                     48
Group E                     48
Group F                     48
Semi-finals                 36
Group G                     30
Group H                     30
Final                       20
Match for third place       15
Group 6                     12
First round                  9
Preliminary round            8
Group 5                      6
Third place                  2
Play-off for third place     2
Name: Stage, dtype: int64
Estadio Azteca               19
Jalisco                      14
Olympiastadion               14
Nou Camp - Estadio Leï¿½n    11
Estadio Centenario           10
                             ..
Comunale di Cornaredo         1
Rimnersvallen                 1
Tunavallen                    1
White City                    1
Eyravallen                    1
Name: Stadium, Length: 181, dtype: int64
Mexico City        23
Montevideo         18
Rio De Janeiro     18
Guadalajara        17
Johannesburg       15
                   ..
Eskilstuna          1
Orebro              1
Reims               1
Antibes             1
Lille               1
Name: City, Length: 151, dtype: int64
Brazil                        82
Italy                         57
Argentina                     54
Germany FR                    43
England                       35
                              ..
Wales                          1
Norway                         1
rn">United Arab Emirates       1
Haiti                          1
rn">Bosnia and Herzegovina     1
Name: Home Team Name, Length: 78, dtype: int64
1.0     246
2.0     205
0.0     177
3.0     116
4.0      59
6.0      17
5.0      17
7.0       8
8.0       4
9.0       2
10.0      1
Name: Home Team Goals, dtype: int64
1.0    323
0.0    313
2.0    140
3.0     52
4.0     14
5.0      7
7.0      3
Name: Away Team Goals, dtype: int64
Mexico               38
France               30
Spain                29
Argentina            27
England              27
                     ..
Dutch East Indies     1
Togo                  1
Cuba                  1
Zaire                 1
Iraq                  1
Name: Away Team Name, Length: 83, dtype: int64
                                                 787
Italy win after extra time                         5
Germany win after extra time                       4
Argentina win after extra time                     4
Belgium win after extra time                       3
Win on Golden Goal                                 3
England win after extra time                       3
Brazil win on penalties (3 - 2)                    3
Netherlands win on penalties (4 - 3)               2
Argentina win on penalties (2 - 4)                 2
France win after extra time                        2
France win on penalties (3 - 4)                    2
Costa Rica win on penalties (5 - 3)                2
 win on penalties (5 - 4)                          1
Germany FR win on penalties (4 - 1)                1
Brazil win after extra time                        1
Czechoslovakia win after extra time                1
Hungary win after extra time                       1
Spain win after extra time                         1
Uruguay win on penalties (4 - 2)                   1
Paraguay win on penalties (5 - 3)                  1
Ghana win after extra time                         1
Italy win on penalties (5 - 3)                     1
Portugal win on penalties (1 - 3)                  1
Germany win on penalties (4 - 2)                   1
Ukraine win on penalties (0 - 3)                   1
Korea Republic win on penalties (3 - 5)            1
Northern Ireland win after extra time              1
Spain win on penalties (3 - 2)                     1
Brazil win on penalties (4 - 2)                    1
Argentina win on penalties (4 - 3)                 1
Germany FR win after extra time                    1
Sweden win on penalties (4 - 5)                    1
Bulgaria win on penalties (1 - 3)                  1
 win on penalties (4 - 3)                          1
Austria win after extra time                       1
 win on penalties (2 - 3)                          1
Yugoslavia win after extra time                    1
Republic of Ireland win on penalties (5 - 4)       1
Cameroon win after extra time                      1
Uruguay win after extra time                       1
Belgium win on penalties (4 - 5)                   1
 win on penalties (3 - 4)                          1
Name: Win conditions, dtype: int64
45000.0    13
43000.0    13
52000.0    11
65000.0     9
25000.0     8
           ..
23800.0     1
55100.0     1
27000.0     1
81100.0     1
20200.0     1
Name: Attendance, Length: 622, dtype: int64
0.0    448
1.0    269
2.0     87
3.0     34
4.0     12
5.0      1
6.0      1
Name: Half-time Home Goals, dtype: int64
0.0    559
1.0    238
2.0     45
3.0      6
5.0      3
4.0      1
Name: Half-time Away Goals, dtype: int64
Ravshan IRMATOV (UZB)             10
RODRIGUEZ Marco (MEX)              8
LARRIONDA Jorge (URU)              8
ARCHUNDIA Benito (MEX)             8
QUINIOU Joel (FRA)                 8
                                  ..
LABO REVOREDO Enrique (PER)        1
ITHURRALDE Arturo Andres (ARG)     1
DWOMOH Benjamin (GHA)              1
ESCHWEILER Walter (GER)            1
Bakary GASSAMA (GAM)               1
Name: Referee, Length: 366, dtype: int64
ACHIK Redouane (MAR)                7
VERGARA Hector (CAN)                7
HERMANS Peter (BEL)                 7
GONZALEZ ARCHUNDIA Alfonso (MEX)    7
BERANEK Alois (AUT)                 7
                                   ..
McCABE George (ENG)                 1
DIAZ GALVEZ Jorge (CHI)             1
SALINAS Reynaldo (HON)              1
ARANGO Jorge Luis (COL)             1
GONZALEZ ROA Gabriel (PAR)          1
Name: Assistant 1, Length: 387, dtype: int64
KOCHKAROV Bakhadyr (KGZ)    10
VERGARA Hector (CAN)         7
YUSTE Juan (ESP)             7
LISTKIEWICZ Michal (POL)     7
VROMANS Walter (BEL)         7
                            ..
TAREKEGN Seyoum (ETH)        1
CHOI Duk Ryong (PRK)         1
DAGNALL Kenneth (ENG)        1
BAKHRAMOV Tofik (URS)        1
KABANDA Felicien (RWA)       1
Name: Assistant 2, Length: 408, dtype: int64
249722.0      48
255931.0      48
43950100.0    48
97410100.0    48
1014.0        48
              ..
3478.0         1
3479.0         1
1028.0         1
1027.0         1
3481.0         1
Name: RoundID, Length: 101, dtype: int64
300186497.0    2
300186502.0    2
300186487.0    2
300186491.0    2
300186462.0    2
              ..
2197.0         1
2246.0         1
2224.0         1
2408.0         1
201.0          1
Name: MatchID, Length: 836, dtype: int64
BRA    82
ITA    57
ARG    54
FRG    43
ENG    35
       ..
TRI     1
BOL     1
JAM     1
HAI     1
BIH     1
Name: Home Team Initials, Length: 77, dtype: int64
MEX    38
FRA    30
ESP    29
ARG    27
ENG    27
       ..
ZAI     1
INH     1
IRQ     1
CUB     1
CZE     1
Name: Away Team Initials, Length: 82, dtype: int64

In [7]:
#Corrigindo textos
jogos_corrigidos = jogos.replace('rn">', '', regex=True)
jogos_corrigidos = jogos_corrigidos.replace('Nou Camp - Estadio Leï¿½n', 'Nou Camp - Estadio León')
jogos_corrigidos = jogos_corrigidos.replace('Stade Vï¿½lodrome', 'Stade Vélodrome')
jogos_corrigidos = jogos_corrigidos.replace('Estadio Olï¿½mpico Chateau Carreras', 'Estadio Olímpico Chateau Carreras')
jogos_corrigidos = jogos_corrigidos.replace('Maracanï¿½ - Estï¿½dio Jornalista Mï¿½rio Filho', 'Maracanã - Estádio Jornalista Mário Filho')
jogos_corrigidos = jogos_corrigidos.replace('Estadio Josï¿½ Marï¿½a Minella', 'Estadio José María Minella ')
jogos_corrigidos = jogos_corrigidos['Year'].astype(int)
jogos_corrigidos

#jogos_corrigidos['Home Team Name'].value_counts()
#jogos_corrigidos['Stadium'].value_counts().head(50)

0      1930
1      1930
2      1930
3      1930
4      1930
       ...
847    2014
848    2014
849    2014
850    2014
851    2014
Name: Year, Length: 852, dtype: int32

In [8]:
jogos_corrigidos

0      1930
1      1930
2      1930
3      1930
4      1930
       ...
847    2014
848    2014
849    2014
850    2014
851    2014
Name: Year, Length: 852, dtype: int32

# Tratando a tabela campeões

In [9]:
campeoes

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [10]:
#adicionando dados da copa de 2018, que não esta no df
campeoes.loc[len(campeoes)] = [2018,'Russia', 'France', 'Croatia', 'Belgium', 'England',169, 32, 64, '3.031.768'] #fonte wikipedia
#campeoes = campeoes.drop([20])
campeoes

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810
20,2018,Russia,France,Croatia,Belgium,England,169,32,64,3.031.768

In [11]:
#corriginndo nome da seleção da alemanha
campeoes_corrigidos = campeoes.replace('Germany FR', 'Germany')
campeoes_corrigidos

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810
20,2018,Russia,France,Croatia,Belgium,England,169,32,64,3.031.768

In [12]:
campeoes_corrigidos.isnull().sum()

Year              0
Country           0
Winner            0
Runners-Up        0
Third             0
Fourth            0
GoalsScored       0
QualifiedTeams    0
MatchesPlayed     0
Attendance        0
dtype: int64

In [13]:
for coluna in campeoes_corrigidos:
    count_campeoes_corrigidos = campeoes_corrigidos[coluna].value_counts()
    print(count_campeoes_corrigidos)

1930    1
1982    1
2014    1
2010    1
2006    1
2002    1
1998    1
1994    1
1990    1
1986    1
1978    1
1934    1
1974    1
1970    1
1966    1
1962    1
1958    1
1954    1
1950    1
1938    1
2018    1
Name: Year, dtype: int64
Italy           2
France          2
Brazil          2
Mexico          2
Germany         2
Uruguay         1
Switzerland     1
Sweden          1
Chile           1
England         1
Argentina       1
Spain           1
USA             1
Korea/Japan     1
South Africa    1
Russia          1
Name: Country, dtype: int64
Brazil       5
Italy        4
Germany      4
Uruguay      2
Argentina    2
France       2
England      1
Spain        1
Name: Winner, dtype: int64
Germany           4
Argentina         3
Netherlands       3
Czechoslovakia    2
Hungary           2
Brazil            2
Italy             2
Sweden            1
France            1
Croatia           1
Name: Runners-Up, dtype: int64
Germany        4
Brazil         2
Sweden         2
France         2
Poland         2
USA            1
Austria        1
Chile          1
Portugal       1
Italy          1
Croatia        1
Turkey         1
Netherlands    1
Belgium        1
Name: Third, dtype: int64
Uruguay           3
Yugoslavia        2
Brazil            2
England           2
Austria           1
Sweden            1
Spain             1
Germany           1
Soviet Union      1
Italy             1
France            1
Belgium           1
Bulgaria          1
Netherlands       1
Korea Republic    1
Portugal          1
Name: Fourth, dtype: int64
70     2
89     2
171    2
132    1
145    1
147    1
161    1
141    1
115    1
146    1
84     1
102    1
97     1
95     1
126    1
140    1
88     1
169    1
Name: GoalsScored, dtype: int64
16    8
32    6
24    4
13    2
15    1
Name: QualifiedTeams, dtype: int64
64    6
52    4
32    3
18    2
38    2
17    1
22    1
26    1
35    1
Name: MatchesPlayed, dtype: int64
590.549      1
2.109.723    1
3.386.810    1
3.178.856    1
3.359.439    1
2.705.197    1
2.785.100    1
3.587.538    1
2.516.215    1
2.394.031    1
1.545.791    1
363.000      1
1.865.753    1
1.603.975    1
1.563.135    1
893.172      1
819.810      1
768.607      1
1.045.246    1
375.700      1
3.031.768    1
Name: Attendance, dtype: int64

# Exportando

In [14]:
jogos_corrigidos.to_csv(r'C:\Users\mathe\OneDrive\Área de Trabalho\Matheus\WorldCup\jogos_corrigidos.csv', header=True,  index=False)
campeoes_corrigidos.to_csv(r'C:\Users\mathe\OneDrive\Área de Trabalho\Matheus\WorldCup\campeoes_corrigidos.csv', header=True, index=False   )